services:
# TODO: Exercise 2: Add services for api- and content services.

# TODO: Exercise 3: Uncomment to launch DynamoDB locally
#  dynamodb-local:
#    image: amazon/dynamodb-local
#    ports:
#      - "8000:8000"
#    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
#
#  init-dynamodb:
#    build: ./local-ddb-helper-image
#    depends_on:
#      - dynamodb-local
#    environment:
#      - CONTENT_NAME_DDB_TABLE_NAME=LOCAL_DDB
#      - AWS_DEFAULT_REGION=local
#      - AWS_ACCESS_KEY_ID=dummy
#      - AWS_SECRET_ACCESS_KEY=dummy
#    command: /bin/bash /scripts/init-dynamodb.sh